language: python

cache: pip

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install counter; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict; fi"

# command to run tests
script:
  - python setup.py build_ext -i
  - python -m compileall -f .
  - python setup.py test
  - coverage run --source=pysvtools setup.py test

after_success:
  - coveralls